export { default as Navigation } from "./Navigation";
export { default as Footer } from "./Footer";
export { default as Home } from "./Home";
export { default as About } from "./About";
export { default as Contact } from "./Contact";
// export { default as Blog } from "./blog/Blog";
// export { default as Posts } from "./blog/Posts";
// export { default as Post } from "./blog/Post";
export { default as Banner } from "./Banner";
export { default as Fabricacao } from "./Fabricacao";
export { default as Logistica } from "./Logistica";
export { default as Slider } from "./Slider";
export { default as BannerHome } from "./BannerHome";
export { default as FormModal } from "./FormModal";